package ly.david.musicsearch.shared.domain.preferences

enum class AppPreferencesKey {
    THEME,
    USE_MATERIAL_YOU,
    SEED_COLOR,
    ARTIST_SORT_OPTION,
    RECORDING_SORT_OPTION,
    RELEASE_SORT_OPTION,
    SHOW_MORE_INFO_IN_RELEASE_LIST_ITEM,
    SHOW_RELEASE_STATUSES,
    RELEASE_GROUP_SORT_OPTION,
    WORK_SORT_OPTION,
    SHOW_LOCAL_COLLECTIONS,
    SHOW_REMOTE_COLLECTIONS,
    HISTORY_SORT_OPTION,
    COLLECTION_SORT_OPTION,
    COVER_ARTS_SORT_OPTION,
    IS_DEVELOPER_MODE,
    NUMBER_OF_IMAGES_PER_ROW,
    IMAGES_GRID_PADDING_DP,
    COLLABORATION_ENTITY_TYPE,
    SCROLL_TO_HIDE_TOP_APP_BAR,

    MUSICBRAINZ_ACCESS_TOKEN,
    MUSICBRAINZ_REFRESH_TOKEN,
    MUSICBRAINZ_EXPIRY_TIME,
    MUSICBRAINZ_USERNAME,

    LISTENBRAINZ_USER_TOKEN,
    LISTENBRAINZ_USER_USERNAME,
    LISTENBRAINZ_BROWSE_USERNAME,

    SPOTIFY_ACCESS_TOKEN,
}
