version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:20"
      timezone: "Canada/Eastern"
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:20"
      timezone: "Canada/Eastern"
    open-pull-requests-limit: 10
