version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:20"
      timezone: "Canada/Eastern"
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:20"
      timezone: "Canada/Eastern"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "androidx.paging:paging-compose"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "androidx.compose.material3:material3"
        update-types: ["version-update:semver-patch"]
