name: "Setup"
description: "Set up gradle"
runs:
  using: "composite"
  steps:
    # https://github.com/gradle/actions
    - uses: gradle/actions/wrapper-validation@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6.1.1

    - name: Configure JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        distribution: "temurin"
        java-version: 21

    - uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6.1.1

    - run: chmod +x gradlew
      shell: bash
