name: "Setup"
description: "Set up gradle"
runs:
  using: "composite"
  steps:
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v3

    - name: Configure JDK
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 19

    # https://github.com/gradle/gradle-build-action
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - run: chmod +x gradlew
      shell: bash
