name: "Setup"
description: "Checkout and set up gradle"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Configure JDK
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "11"

    # https://github.com/gradle/gradle-build-action
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - run: chmod +x gradlew
      shell: bash
