name: "Setup"
description: "Set up gradle"
runs:
  using: "composite"
  steps:
    # https://github.com/gradle/actions
    - uses: gradle/actions/wrapper-validation@06832c7b30a0129d7fb559bcc6e43d26f6374244 #v4.3.1

    - name: Configure JDK
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: "temurin"
        java-version: 21

    - uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 #v4.3.1

    - run: chmod +x gradlew
      shell: bash
