name: "Setup"
description: "Set up gradle"
runs:
  using: "composite"
  steps:
    # https://github.com/gradle/actions
    - uses: gradle/actions/wrapper-validation@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2

    - name: Configure JDK
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: "temurin"
        java-version: 21

    - uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2

    - run: chmod +x gradlew
      shell: bash
