version: 2.1

orbs:
  android: circleci/android@2.2.0
  codecov: codecov/codecov@3.2.4

# TODO: Running into https://issuetracker.google.com/issues/235259765 sometimes

parameters:
  run_android_test:
    type: boolean
    default: false

jobs:
  android-test:
    environment:
      GRADLE_USER_HOME: "~/.gradle"
      JVM_OPTS: -Xmx8g
    executor:
      name: android/android-machine
      resource-class: large
      # https://circleci.com/developer/images/image/cimg/android#image-tags
      tag: 2023.05.1
    steps:
      - checkout

      - run: chmod +x gradlew

      - run: mkdir -p ~/.gradle ; cp .ci/ci-gradle.properties ~/.gradle/gradle.properties

      - android/change-java-version:
          java-version: 17

      - android/create-avd:
          avd-name: test
          install: true
          system-image: system-images;android-30;google_apis;x86

      - run: cat .circleci/test_avd_config >> ~/.android/avd/test.avd/config.ini

      - android/start-emulator:
          avd-name: test
          post-emulator-launch-assemble-command: ./gradlew app:assembleDebugAndroidTest

      - android/run-tests:
          max-tries: 2
          test-command: ./gradlew app:createDebugAndroidTestCoverageReport --stacktrace

      - store_artifacts:
          path: app/build/reports/androidTests/connected
      - codecov/upload:
          file: app/build/reports/coverage/androidTest/debug/connected/report.xml

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/
            find . -type f -regex ".*/build/outputs/androidTest-results/connected/.*xml" -exec cp {} ~/test-results/ \;
          when: always
      - store_test_results:
          path: ~/test-results

workflows:
  test-and-build:
    when: << pipeline.parameters.run_android_test >>
    jobs:
      - android-test
