version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          base-revision: master
          config-path: .circleci/android_test.yml
          mapping: |
            .ci/.* run_android_test true
            .circleci/.* run_android_test true
            .*src.*\.kt run_android_test true
            .*\.gradle run_android_test true
            .*\.gradle\.kts run_android_test true
