version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  determine-what-to-run:
    jobs:
      - path-filtering/filter:
          base-revision: master
          config-path: .circleci/android_test.yml
          mapping: |
            .ci/.* run_android_test true
            .circleci/.* run_android_test true
            .*src.*\.kt run_android_test true
            .*\.gradle run_android_test true
            .*\.gradle\.kts run_android_test true
            gradle/.* run_android_test true
            gradlew run_android_test true
            gradlew.bat run_android_test true
            .*AndroidManifest\.xml run_android_test true
