[versions]
aboutlibraries = "10.9.2"
accompanist = "0.32.0"
androidGradlePlugin = "8.2.0"
chucker = "4.0.0"
coil = "2.5.0"
compose-compiler = "1.5.6"
compose-foundation = "1.5.4"
compose-material = "1.5.4"
compose-material3 = "1.1.2"
compose-multiplatform = "1.5.11"
compose-ui = "1.5.4"
datastore = "1.0.0"
detekt = "1.23.4"
junit = "4.13.2"
koin = "3.5.0"
koinAnnotations = "1.3.0"
koinCompose = "3.5.0"
kotlin = "1.9.21"
kotlinx-coroutines = "1.7.1"
ksp = "1.9.21-1.0.16"
leakcanaryAndroid = "2.12"
lyricist = "1.6.2"
mockk = "1.13.8"
okhttp = "4.12.0"
paging = "3.2.1"
pagingMultiplatform = "3.2.0-alpha05-0.2.3"
paparazzi = "1.3.1"
sqldelight = "2.0.0"

[libraries]
aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutlibraries" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
# build-logic libraries
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
androidx-activity-compose = "androidx.activity:activity-compose:1.8.2"
androidx-arch-core-testing = "androidx.arch.core:core-testing:2.2.0"
androidx-constraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.0.1"
androidx-core = "androidx.core:core-ktx:1.12.0"
androidx-datastore-preferences-android = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
#androidx-datastore-preferences-jvm = { group = "androidx.datastore", name = "datastore-preferences-jvm", version.ref = "datastore" }
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.2"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.7.6"
androidx-paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
androidx-test-junit = "androidx.test.ext:junit:1.1.5"
appauth = "net.openid:appauth:0.11.1"
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-noop = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
coil-base = { module = "io.coil-kt:coil-base", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-test = { module = "io.coil-kt:coil-test", version.ref = "coil" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-foundation" }
compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-multiplatform" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-material" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
desugarjdklibs = "com.android.tools:desugar_jdk_libs:2.0.4"
detekt-compose = "io.nlopez.compose.rules:detekt:0.3.6"
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-gradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = "com.google.firebase:firebase-bom:32.7.0"
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinCompose" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koinAnnotations" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinAnnotations" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.6"
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.5.0"
ksp-gradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
ktor-bom = "io.ktor:ktor-bom:2.3.7"
ktor-client-auth = { module = "io.ktor:ktor-client-auth" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
lyricist-library = { module = "cafe.adriel.lyricist:lyricist", version.ref = "lyricist" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
paging-common = { module = "app.cash.paging:paging-common", version.ref = "pagingMultiplatform" }
paging-compose = { module = "app.cash.paging:paging-runtime-composeui", version.ref = "pagingMultiplatform" }
paparazzi = { module = "app.cash.paparazzi:paparazzi", version.ref = "paparazzi" }
robolectric = "org.robolectric:robolectric:4.11.1"
scribejava = "com.github.scribejava:scribejava-apis:8.3.3"
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-paging = { module = "app.cash.sqldelight:androidx-paging3-extensions", version.ref = "sqldelight" }
sqldelight-primitive = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
test-parameter-injector = "com.google.testparameterinjector:test-parameter-injector:1.14"
timber = "com.jakewharton.timber:timber:5.0.1"

[bundles]
kotlinx-coroutines = [
    "kotlinx-coroutines-android",
    "kotlinx-coroutines-test",
]
ktor-jvm = [
    "ktor-client-auth",
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-client-logging",
    "ktor-client-okhttp",
    "ktor-serialization-kotlinx-json",
]

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
build-config = "com.github.gmazzo.buildconfig:4.2.0"
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
dependency-analysis = "com.autonomousapps.dependency-analysis:1.28.0"
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
firebase-crashlytics = "com.google.firebase.crashlytics:2.9.9"
google-services = "com.google.gms.google-services:4.4.0"
gradle-versions = "com.github.ben-manes.versions:0.50.0"
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.1"
