complexity:
  CyclomaticComplexMethod:
    ignoreSimpleWhenEntries: true
    ignoreSingleWhenExpression: true
  LongParameterList:
    active: false
  LongMethod:
    ignoreAnnotated:
      - "Composable"
      - "Test"
  TooManyFunctions:
    active: false
exceptions:
  TooGenericExceptionCaught:
    active: false
formatting:
  ImportOrdering:
    active: false
  MaximumLineLength:
    active: false
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
style:
  ForbiddenComment:
    active: false
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreAnnotated:
      - "DefaultPreviews"
      - "Test"
  MaxLineLength:
    excludeCommentStatements: true
    ignoreAnnotated:
      - "Test"
  ReturnCount:
    excludeGuardClauses: true
  UnusedPrivateProperty:
    allowedNames: '(_|ignored|expected|((android(UnitTest|InstrumentedTest)?|common|ios|jvm)(Main|Test)?))'
  UnusedPrivateMember:
    ignoreAnnotated:
      - "DefaultPreviews"
      - "Preview"
coroutines:
  GlobalCoroutineUsage:
    active: true
  SuspendFunSwallowedCancellation:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true
