complexity:
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated:
      - "Composable"
  LongMethod:
    ignoreAnnotated:
      - "Composable"
  TooManyFunctions:
    active: false
naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated:
      - "DefaultPreviews"
      - "Preview"
