complexity:
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated:
      - "Composable"
  LongMethod:
    ignoreAnnotated:
      - "Composable"
naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
