complexity:
  CyclomaticComplexMethod:
    ignoreSimpleWhenEntries: true
  LongParameterList:
    active: false
  LongMethod:
    ignoreAnnotated:
      - "Composable"
  TooManyFunctions:
    active: false
formatting:
  ImportOrdering:
    active: false
  MaximumLineLength:
    active: false
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
style:
  ForbiddenComment:
    active: false
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreAnnotated:
      - "DefaultPreviews"
      - "Test"
  MaxLineLength:
    ignoreAnnotated:
      - "Test"
  ReturnCount:
    excludeGuardClauses: true
  UnusedPrivateMember:
    ignoreAnnotated:
      - "DefaultPreviews"
      - "Preview"
