name: Checks (app)

on:
  push:
    paths-ignore:
      - "*.md"
      - ".circleci/config.yml"

jobs:
  checks:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: setup
        uses: ./.github/actions/setup

      - name: Detekt
        run: ./gradlew app:detekt

      - name: Run app unit tests with coverage
        run: ./gradlew app:createDebugUnitTestCoverageReport
