name: Checks

on:
  push:
    paths-ignore:
      - "**.md"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # When we change the name of this job, make sure to update GitHub's branch protection to the new name
  checks:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@385a8ecc719e50b8c71af6ab01a624b486b7c3bc # v1
        with:
          token: ${{ secrets.PAT }}

      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: false
          android: false
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: true

      - id: setup
        uses: ./.github/actions/setup

      - uses: szenius/set-timezone@1f9716b0f7120e344f0c62bb7b1ee98819aefd42 # v2.0
        with:
          timezoneLinux: "America/Toronto"

      - name: Konsist architecture unit tests
        run: ./gradlew konsist-test:test --rerun-tasks

      - name: Detekt code smells in commonMain
        if: ${{ !cancelled() }}
        run: ./gradlew detektMetadataCommonMain

      - name: Detekt code smells in iosMain
        if: ${{ !cancelled() }}
        run: ./gradlew detektMetadataIosMain

      - name: Detekt code smells in jvmMain
        if: ${{ !cancelled() }}
        run: ./gradlew detektJvmMain

      - name: Detekt code smells in android
        if: ${{ !cancelled() }}
        run: ./gradlew detektAndroidDebug detektAndroidRelease

      - name: Detekt code smells in android tests
        if: ${{ !cancelled() }}
        run: ./gradlew detektAndroidDebugUnitTest

      # Includes non-KMP detekt, verifySqlDelightMigration
      - name: Perform checks on all modules
        if: ${{ !cancelled() }}
        run: ./gradlew check

      - name: Verify screenshot tests
        id: screenshotsverify
        if: ${{ !cancelled() }}
        run: ./gradlew verifyPaparazziDebug

      - name: Delete all snapshot golden
        if: ${{ !cancelled() && steps.screenshotsverify.outcome == 'failure' }}
        run: find . -type f ! -path '*/build/*' -a -path '*/snapshots/images/*' | xargs -I {} rm {}

      - name: Generate new screenshots if verification failed
        id: screenshotsrecord
        if: ${{ !cancelled() && steps.screenshotsverify.outcome == 'failure' && !startsWith(github.ref, 'refs/heads/renovate/') }}
        run: |
          ./gradlew recordPaparazziDebug

      - name: Push new screenshots if available
        if: ${{ !cancelled() && steps.screenshotsrecord.outcome == 'success' }}
        run: |
          git pull --autostash
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add '**\/*.png'
          git commit -m "chore: rerecord snapshot tests [skip ci]" || echo "No changes to commit"
          git push

  ios-checks:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - id: setup
        uses: ./.github/actions/setup

      - run: ./gradlew iosSimulatorArm64Test
