name: Checks

on:
  push:
    paths-ignore:
      - "*.md"
      - ".circleci/config.yml"

jobs:
  # When we change the name of this job, make sure to update GitHub's branch protection to the new name
  checks:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#        with:
#          lfs: true

      - id: setup
        uses: ./.github/actions/setup

      - name: Detekt code smells
        run: ./gradlew detekt

      - name: Unit test :data:base
        uses: gradle/gradle-build-action@v2
        with:
          arguments: data:base:test

      - name: Unit test :data:coverart
        uses: gradle/gradle-build-action@v2
        with:
          arguments: data:coverart:test

      - name: Unit test :data:domain
        uses: gradle/gradle-build-action@v2
        with:
          arguments: data:domain:test

      - name: Unit test data:musicbrainz
        uses: gradle/gradle-build-action@v2
        with:
          arguments: data:musicbrainz:test

      - name: Unit test :data:room
        uses: gradle/gradle-build-action@v2
        with:
          arguments: data:room:test

      - name: Unit test data:spotify
        uses: gradle/gradle-build-action@v2
        with:
          arguments: data:spotify:test

#      - name: Verify screenshot tests
#        run: ./gradlew verifyPaparazziDebug

      # TODO: Neither of these actually test code from their own module, so we're getting 0%
      - name: Unit test Android modules with coverage
        run: ./gradlew app:createDebugUnitTestCoverageReport data-android:createDebugUnitTestCoverageReport
