name: Checks

on:
  push:
    paths-ignore:
      - "**.md"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # When we change the name of this job, make sure to update GitHub's branch protection to the new name
  checks:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Toronto"

      - name: Konsist architecture unit tests
        run: ./gradlew konsist-test:test --rerun-tasks

      # https://github.com/detekt/detekt/issues/3665
      - name: Detekt KMP code smells
        if: always()
        run: ./gradlew detektMetadataMain

      # Includes detekt, verifySqlDelightMigration
      - name: Perform checks on all modules
        if: always()
        run: ./gradlew check

      - name: Verify screenshot tests
        id: screenshotsverify
        if: always()
        run: ./gradlew verifyPaparazziDebug

      - name: Delete all snapshot golden
        if: always() && steps.screenshotsverify.outcome == 'failure'
        run: find . -type f ! -path '*/build/*' -a -path '*/snapshots/images/*' | xargs -I {} rm {}

      - name: Generate new screenshots if verification failed
        id: screenshotsrecord
        if: always() && steps.screenshotsverify.outcome == 'failure'
        run: |
          ./gradlew recordPaparazziDebug

      - run: git pull --rebase --autostash
        if: always() && steps.screenshotsrecord.outcome == 'success'

      - name: Generate GitHub app token so that commit can trigger new workflow run
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.MUSICSEARCH_GHA_HELPER_APP_ID }}
          private_key: ${{ secrets.MUSICSEARCH_GHA_HELPER_APP_PRIVATE_KEY }}

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        if: always() && steps.screenshotsrecord.outcome == 'success'
        with:
          commit_message: "chore: rerecord snapshot tests"
          token: ${{ steps.generate-token.outputs.token }}
          commit_user_name: musicsearch-gha-helper[bot]
          commit_user_email: 173635759+musicsearch-gha-helper[bot]@users.noreply.github.com
          commit_author: musicsearch-gha-helper[bot] <173635759+musicsearch-gha-helper[bot]@users.noreply.github.com>
          disable_globbing: true
          file_pattern: '*/*.png'

      - name: Save
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: |
            shared/domain/build/reports/tests/
  ios-checks:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: setup
        uses: ./.github/actions/setup

      - run: ./gradlew iosSimulatorArm64Test
