name: Checks

on:
  push:
    paths-ignore:
      - "*.md"
      - ".circleci/config.yml"

jobs:
  # When we change the name of this job, make sure to update GitHub's branch protection to the new name
  checks:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - id: setup
        uses: ./.github/actions/setup

      - name: Detekt code smells
        run: ./gradlew detekt

      - name: Unit test all kotlin modules
        run: ./gradlew testKotlinModules

      - name: Verify screenshot tests
        run: ./gradlew verifyPaparazziDebug

      # TODO: Neither of these actually test code from their own module, so we're getting 0%
      - name: Unit test Android modules with coverage
        run: ./gradlew app:createDebugUnitTestCoverageReport data-android:createDebugUnitTestCoverageReport
