name: Checks

on:
  push:
    paths-ignore:
      - "*.md"

jobs:
  # When we change the name of this job, make sure to update GitHub's branch protection to the new name
  checks:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - id: setup
        uses: ./.github/actions/setup

      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Toronto"

      - name: Detekt non-KMP code smells
        if: always()
        run: ./gradlew detekt

      # https://github.com/detekt/detekt/issues/3665
      - name: Detekt KMP code smells
        if: always()
        run: ./gradlew detektMetadataMain

      - name: Unit test all kotlin modules
        if: always()
        run: ./gradlew testKotlinModules

      - name: Unit test all KMP modules
        if: always()
        run: ./gradlew testKotlinMultiplatformModules

      - name: Verify screenshot tests
        id: screenshotsverify
        if: always()
        run: ./gradlew verifyPaparazziDebug

      # Runs if previous job failed
      - name: Generate new screenshots if verification failed and it's a PR
        id: screenshotsrecord
        if: always() && steps.screenshotsverify.outcome == 'failure'
        run: |
          ./gradlew recordPaparazziDebug

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        if: always() && steps.screenshotsrecord.outcome == 'success'
        with:
          file_pattern: '*/*.png'
          disable_globbing: true
          commit_message: "chore: rerecord snapshot tests"
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
