name: Checks

on:
  push:
    paths-ignore:
      - "*.md"
      - ".circleci/config.yml"

jobs:
  # When we change the name of this job, make sure to update GitHub's branch protection to the new name
  checks:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - id: setup
        uses: ./.github/actions/setup

      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Toronto"

      - name: Detekt non-KMP code smells
        continue-on-error: true
        run: ./gradlew detekt

      # https://github.com/detekt/detekt/issues/3665
      - name: Detekt KMP code smells
        continue-on-error: true
        run: ./gradlew detektMetadataMain

      - name: Unit test all kotlin modules
        continue-on-error: true
        run: ./gradlew testKotlinModules

      - name: Unit test all KMP modules
        continue-on-error: true
        run: ./gradlew testKotlinMultiplatformModules

      - name: Verify screenshot tests
        id: screenshotsverify
        continue-on-error: true
        run: ./gradlew verifyPaparazziDebug

      - name: Prevent pushing new screenshots if this is a fork
        id: checkfork_screenshots
        continue-on-error: false
        if: steps.screenshotsverify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "::error::Screenshot tests failed, please create a PR in your fork first." && exit 1

      # Runs if previous job failed
      - name: Generate new screenshots if verification failed and it's a PR
        id: screenshotsrecord
        if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
        run: |
          ./gradlew recordPaparazziDebug

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        if: steps.screenshotsrecord.outcome == 'success'
        with:
          file_pattern: '*/*.png'
          disable_globbing: true
          commit_message: "chore: updates screenshots"
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
