name: Checks

on:
  push:
    paths-ignore:
      - "*.md"
      - ".circleci/config.yml"

jobs:
  # When we change the name of this job, make sure to update GitHub's branch protection to the new name
  checks:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - id: setup
        uses: ./.github/actions/setup

      - name: Detekt non-KMP code smells
        run: ./gradlew detekt

      # https://github.com/detekt/detekt/issues/3665
      - name: Detekt KMP code smells
        run: ./gradlew detektMetadataMain

      - name: Unit test all kotlin modules
        run: ./gradlew testKotlinModules

      - name: Unit test all KMP modules
        run: ./gradlew testKotlinMultiplatformModules

      - name: Verify screenshot tests
        run: ./gradlew verifyPaparazziDebug
