name: "Create issue from TODO comments"
on:
  push:
    branches:
      - main
jobs:
  create-todo:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: "Create issue from TODO comments"
        uses: alstr/todo-to-issue-action@64aca8fda7023259aada83ba44ad988c4c443657 # v5
