name: Nightly chores

on:
  schedule:
    - cron: '42 4 * * *'
  workflow_dispatch:

jobs:
  regenerate-graph:
    name: Regenerate graph
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - run: sudo apt install graphviz

      - run: ./gradlew projectDependencyGraph

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: 'chore: update module dependency graph [skip ci]'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

  format-version-catalog:
    name: Format version catalog
    needs: regenerate-graph
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - run: ./gradlew versionCatalogFormat

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: 'chore: format version catalog [skip ci]'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
