name: Nightly chores

on:
  schedule:
    - cron: '42 4 * * *'
  workflow_dispatch:

jobs:
  update-schema-diagram:
    permissions:
      contents: write
    uses: ./.github/workflows/update-dependency-graph.yml
    secrets:
      PAT: ${{ secrets.PAT }}

  format-version-catalog:
    name: Format version catalog
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@f46300cd8952454b9f0a21a3d133d4bd5684cfc2 # v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - run: ./gradlew versionCatalogFormat

      - run: git pull --rebase --autostash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@3cc016cfc892e0844046da36fc68da4e525e081f # v6.0.0
        with:
          commit_message: 'chore: format version catalog [skip ci]'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
