name: Nightly chores

on:
  schedule:
    - cron: '42 4 * * *'
  workflow_dispatch:

jobs:
  update-schema-diagram:
    permissions:
      contents: write
    uses: ./.github/workflows/update-dependency-graph.yml
    secrets:
      PAT: ${{ secrets.PAT }}

  format-version-catalog:
    name: Format version catalog
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@f46300cd8952454b9f0a21a3d133d4bd5684cfc2 # v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - run: ./gradlew versionCatalogFormat

      - name: Commit
        run: |
          git pull --rebase --autostash
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "chore: format version catalog [skip ci]"
          git push
