name: Nightly chores

on:
  schedule:
    - cron: '42 4 * * *'
  workflow_dispatch:

jobs:
  update-schema-diagram:
    permissions:
      contents: write
    uses: ./.github/workflows/update-dependency-graph.yml
    secrets:
      PAT: ${{ secrets.PAT }}

  format-version-catalog:
    name: Format version catalog
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - run: ./gradlew versionCatalogFormat

      - run: git pull --rebase --autostash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: 'chore: format version catalog [skip ci]'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

  regenerate-licenses:
    name: Regenerate licenses
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - run: ./gradlew desktop:app:exportLibraryDefinitions -PaboutLibraries.exportPath=src/main/resources/

      - run: git pull --rebase --autostash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: 'chore: update licenses [skip ci]'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
