name: Publish

on:
  workflow_call:
    inputs:
      track:
        required: true
        type: string
    secrets:
      PAT:
        required: true
      MUSICSEARCH_GHA_HELPER_APP_ID:
        required: true
      MUSICSEARCH_GHA_HELPER_APP_PRIVATE_KEY:
        required: true
      ORG_GRADLE_PROJECT_MUSICBRAINZ_CLIENT_ID:
        required: true
      ORG_GRADLE_PROJECT_MUSICBRAINZ_CLIENT_SECRET:
        required: true
      ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_ID:
        required: true
      ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_SECRET:
        required: true
      RELEASE_STORE_PASSWORD:
        required: true
      RELEASE_KEY_PASSWORD:
        required: true
      GOOGLE_SERVICES_JSON_BASE64:
        required: true
      RELEASE_KEYSTORE_JKS_BASE64:
        required: true
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      SERVICE_ACCOUNT:
        required: true
      SIGNING_KEY:
        required: true

jobs:
  check:
    if: ${{ inputs.track }} != 'production'
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early_exit.outputs.status }}
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      # Cannot early exit jobs with GHA yet
      # Workaround: https://github.com/actions/runner/issues/662#issuecomment-1372855726
      - name: Determine whether to exit early if previous commit was a version bump
        id: early_exit
        run: |
          status='skip'
          if ! (git log --oneline -n 1 | grep -c 'chore\: bump version \[skip ci\]'); then status='deploy'; fi
          echo "status=$status" >> $GITHUB_OUTPUT
        shell: bash

  checks:
    needs: check
    if: needs.check.outputs.status == 'deploy' || ${{ inputs.track }} == 'production'
    permissions:
      contents: write
    uses: ./.github/workflows/checks.yml
    secrets:
      PAT: ${{ secrets.PAT }}
      MUSICSEARCH_GHA_HELPER_APP_ID: ${{ secrets.MUSICSEARCH_GHA_HELPER_APP_ID }}
      MUSICSEARCH_GHA_HELPER_APP_PRIVATE_KEY: ${{ secrets.MUSICSEARCH_GHA_HELPER_APP_PRIVATE_KEY }}

  test-e2e:
    needs: check
    if: needs.check.outputs.status == 'deploy' || ${{ inputs.track }} == 'production'
    permissions:
      contents: write
    uses: ./.github/workflows/test-e2e.yml
    secrets:
      PAT: ${{ secrets.PAT }}

  publish:
    needs:
      - checks
      - test-e2e
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # This is required for requesting the JWT
    env:
      ORG_GRADLE_PROJECT_MUSICBRAINZ_CLIENT_ID: ${{ secrets.ORG_GRADLE_PROJECT_MUSICBRAINZ_CLIENT_ID }}
      ORG_GRADLE_PROJECT_MUSICBRAINZ_CLIENT_SECRET: ${{ secrets.ORG_GRADLE_PROJECT_MUSICBRAINZ_CLIENT_SECRET }}
      ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_ID: ${{ secrets.ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_ID }}
      ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_SECRET: ${{ secrets.ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - name: Setup gradle
        uses: ./.github/actions/setup

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup semantic-release
        run: npm install

      - name: Get next release version
        id: get-next-version
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      # -b preserves our line separator preference
      - name: Bump version code
        run: |
          VC=$(grep 'VERSION_CODE' gradle.properties | cut -d = -f 2)
          sed -bi "s/VERSION_CODE=$VC/VERSION_CODE=$(($VC + 1))/" gradle.properties
        shell: bash

      - name: Bump version name
        if: steps.get-next-version.outputs.new-release-published == 'true'
        run: |
          VN=$(grep 'VERSION_NAME' gradle.properties | cut -d = -f 2)
          newVN=${{ steps.get-next-version.outputs.new-release-version }}
          sed -bi "s/VERSION_NAME=$VN/VERSION_NAME=$newVN/" gradle.properties
        shell: bash

      # After this step, the workspace contains credentials file.
      # Take care not to commit it or upload artifacts with it.
      - name: Write to keystore.properties
        run: |
          echo "storePassword=${{ secrets.RELEASE_STORE_PASSWORD }}" >> keystore.properties
          echo "keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> keystore.properties
        shell: bash

      - name: Convert base64 to files
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d >> android/app/google-services.json
          echo "${{ secrets.RELEASE_KEYSTORE_JKS_BASE64 }}" | base64 -d >> release-keystore.jks
        shell: bash

      - name: Assemble apk, bundle aab
        run: ./gradlew assembleRelease bundleRelease

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.4
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Publish build to Google Play
        id: publish_play_store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: io.github.lydavid.musicsearch
          track: ${{ inputs.track }}
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          mappingFile: android/app/build/outputs/mapping/release/mapping.txt

      - name: Create jars
        if: steps.get-next-version.outputs.new-release-published == 'true'
        run: ./gradlew jar

      - name: Create desktop distributions
        uses: hydraulic-software/conveyor/actions/build@v14.3
        if: steps.get-next-version.outputs.new-release-published == 'true'
        with:
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          command: make site

      - run: |
          mv output/download.html .
          mv output/icon.svg .
        if: steps.get-next-version.outputs.new-release-published == 'true'

      - name: Commit version code bump
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        if: always()
        with:
          commit_message: 'chore: bump version [skip ci]'
          file_pattern: 'gradle.properties download.html icon.svg'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

      # See .releaserc for the artifacts we include in each release
      - name: Publish to GitHub
        if: steps.get-next-version.outputs.new-release-published == 'true'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Merge master back into beta
        if: always() && ${{ inputs.track }} != 'beta'
        run: |
          git checkout beta
          git merge master --ff-only --no-edit
          git push origin beta
