name: Publish internal build

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early_exit.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Cannot early exit jobs with GHA yet
      # Workaround: https://github.com/actions/runner/issues/662#issuecomment-1372855726
      - name: Determine whether to exit early based on previous commit
        id: early_exit
        run: |
          status='skip'
          if ! (git log --oneline -n 1 | grep -c 'chore: bump version'); then status='deploy'; fi
          echo "status=$status" >> $GITHUB_OUTPUT
        shell: bash

  publish-internal:
    needs: check
    if: needs.check.outputs.status == 'deploy'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # This is required for requesting the JWT
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup semantic-release
        run: npm install

      - name: Get next release version
        id: get-next-version
        run: npx semantic-release --dry-run
        with:
          token: ${{ secrets.PAT }}

      # -b preserves our line separator preference
      - name: Bump version code
        run: |
          VC=$(grep 'versionCode' app/build.gradle.kts | sed 's/[^0-9]//g')
          sed -bi "s/versionCode = $VC/versionCode = $(($VC + 1))/" app/build.gradle.kts
        shell: bash

      - name: Bump version name
        run: |
          VN=$(grep 'version' gradle.properties | sed 's/[^0-9.]//g')
          newVN=${{ steps.get-next-version.outputs.new-release-version }}
          sed -bi "s/version = \"$VN\"/version = $newVN/" gradle.properties
        shell: bash

      # After this step, the workspace contains credentials file.
      # Take care not to commit it or upload artifacts with it.
      - name: Write to keystore.properties
        run: |
          echo "storePassword=${{ secrets.RELEASE_STORE_PASSWORD }}" >> keystore.properties
          echo "keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> keystore.properties
        shell: bash

      - name: Convert base64 to files
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d >> app/google-services.json
          echo "${{ secrets.RELEASE_KEYSTORE_JKS_BASE64 }}" | base64 -d >> release-keystore.jks
        shell: bash

      - name: Assemble and bundle app
        run: ./gradlew assemble bundle

      - name: Release to GitHub
        id: publish_github
        run: npx semantic-release
        with:
          token: ${{ secrets.PAT }}

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.0.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Publish build to Google Play's internal track
        id: publish_play_store
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: io.github.lydavid.musicsearch
          track: internal
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          mappingFile: app/build/outputs/mapping/release/mapping.txt

      - name: Commit version code bump
        if: |
          steps.publish_github.outcome == 'success' &&
          steps.publish_play_store.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: 'chore: bump version'
          file_pattern: 'app/build.gradle.kts gradle.properties'
