name: Publish production build
run-name: "Publish production build from ${{ github.sha }}"

on:
  workflow_dispatch:

jobs:
  publish-production:
    permissions:
      contents: write
      id-token: write
      pages: write
    uses: ./.github/workflows/publish.yml
    with:
      track: production
    secrets: inherit
