name: Publish

on:
  workflow_call:
    inputs:
      track:
        required: true
        type: string

jobs:
  checks:
    permissions:
      contents: write
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  test-e2e:
    permissions:
      contents: write
    uses: ./.github/workflows/test-e2e.yml
    secrets: inherit

  publish:
    needs:
      - checks
      - test-e2e
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write # This is required for requesting the JWT
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - name: Setup gradle
        uses: ./.github/actions/setup

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup semantic-release
        run: npm install

      - name: Get next release version
        id: get-next-version
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      # -b preserves our line separator preference
      - name: Bump version code
        run: |
          VC=$(grep 'VERSION_CODE' gradle.properties | cut -d = -f 2)
          sed -bi "s/VERSION_CODE=$VC/VERSION_CODE=$(($VC + 1))/" gradle.properties
        shell: bash

      - name: Bump version name
        if: steps.get-next-version.outputs.new-release-published == 'true'
        run: |
          VN=$(grep 'VERSION_NAME' gradle.properties | cut -d = -f 2)
          newVN=${{ steps.get-next-version.outputs.new-release-version }}
          sed -bi "s/VERSION_NAME=$VN/VERSION_NAME=$newVN/" gradle.properties
        shell: bash

      # After this step, the workspace contains credentials file.
      # Take care not to commit it or upload artifacts with it.
      - name: Write to keystore.properties
        run: |
          echo "storePassword=${{ secrets.RELEASE_STORE_PASSWORD }}" >> keystore.properties
          echo "keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> keystore.properties
        shell: bash

      # Necessary because the debug and release version of the app has a different redirect
      - name: Replace debug MusicBrainz client id/secret with release versions
        run: |
          echo "TVVTSUNCUkFJTlpfQ0xJRU5UX0lEPWtpbVpiWXlaYUVia2Ewb0Npb1ExNUdINWhlNFp4dGtXCg==" | base64 -d > not_so_secret.properties
          echo "TVVTSUNCUkFJTlpfQ0xJRU5UX1NFQ1JFVD00ZVlINmpqRzBVVm1GRGN1Yk1CSThrVVlxT18xVkxHRAo=" | base64 -d >> not_so_secret.properties

      - name: Decrypt release keystore
        run: echo "${{ secrets.RELEASE_KEYSTORE_JKS_BASE64 }}" | base64 -d > release-keystore.jks

      - name: Assemble F-Droid APK
        id: build-fdroid
        run: |
          sed -i -e '/firebase/d' -e '/google.services/d' build.gradle.kts
          ./gradlew clean assembleFDroidRelease

      - name: Decrypt Google Services file
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json

      - name: Assemble Google Play APK, bundle AAB
        id: build-google
        run: |
          git restore build.gradle.kts
          ./gradlew assembleGooglePlayRelease bundleGooglePlayRelease
        env:
          ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_ID: ${{ secrets.ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_ID }}
          ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_SECRET: ${{ secrets.ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_SECRET }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.8
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      # This step may fail if we rerun because we have already uploaded this version
      # so subsequent steps should always run
      - name: Publish build to Google Play
        id: publish_play_store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: io.github.lydavid.musicsearch
          track: ${{ inputs.track }}
          releaseFiles: android/app/build/outputs/bundle/googlePlayRelease/app-googlePlay-release.aab
          mappingFile: android/app/build/outputs/mapping/googlePlayRelease/mapping.txt

      - name: Create jars
        if: always() && steps.get-next-version.outputs.new-release-published == 'true'
        run: ./gradlew jar
        env:
          ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_ID: ${{ secrets.ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_ID }}
          ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_SECRET: ${{ secrets.ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_SECRET }}

      - name: Create desktop distributions
        if: always() && steps.get-next-version.outputs.new-release-published == 'true'
        uses: hydraulic-software/conveyor/actions/build@v17.0
        with:
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          command: make site

      - run: |
          mv output/download.html .
          mv output/icon.svg .
        if: always() && steps.get-next-version.outputs.new-release-published == 'true'

      - name: Commit version code bump
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        if: always()
        with:
          commit_message: 'chore: bump version [skip ci]'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          file_pattern: 'gradle.properties download.html icon.svg'

      # See .releaserc for the artifacts we include in each release
      - name: Publish to GitHub
        if: always() && steps.get-next-version.outputs.new-release-published == 'true'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  publish-gh-pages:
    needs: publish
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/jekyll-gh-pages.yml
