name: Publish production build

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  publish-production:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/publish.yml
    with:
      track: production
    secrets: inherit
