name: Publish build

on:
  workflow_dispatch:

jobs:
  publish:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup semantic-release
        run: npm install

      # Make sure this file doesn't show up in the packaged release
      - run: touch findme.txt

      - name: Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: npx semantic-release
