name: Publish production build
run-name: "Publish production build from ${{ github.sha }}"

on:
  workflow_dispatch:
    inputs:
      skip-desktop:
        required: true
        type: boolean
        default: false
        description: Skip desktop release

jobs:
  publish-production:
    permissions:
      contents: write
      id-token: write
      pages: write
    uses: ./.github/workflows/publish.yml
    with:
      track: production
      skip-desktop: ${{ inputs.skip-desktop }}
    secrets: inherit
