name: Record Screenshot Tests

on:
  pull_request:

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: ./.github/actions/setup

    - name: Record screenshot tests
      run: ./gradlew recordPaparazziDebug

    - name: Configure git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit screenshots
      run: |
        git add app/src/test/java/com/example/app/screenshots
        git commit -m "Update screenshot tests [skip ci]"
        git push origin HEAD:${{ github.head_ref }}