name: Record Screenshot Tests

on:
  issue_comment:
    types: [created]

jobs:
  record:
    permissions:
      contents: write
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/record')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: ./.github/actions/setup

    - name: Record screenshot tests
      run: ./gradlew recordPaparazziDebug

    - name: Commit screenshots
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: 'Update screenshot tests [skip ci]'