name: Record snapshot tests

on:
  issue_comment:
    types:
      - created

jobs:
  record:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/record' }}
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - id: setup
        uses: ./.github/actions/setup

      # Renamed and deleted test functions are not automatically removed by Paparazzi
      - name: Delete all snapshot golden
        run: find . -type f ! -path '*/build/*' -a -path '*/snapshots/images/*' | xargs rm

      - name: Record snapshots
        run: ./gradlew recordPaparazziDebug

      - name: Commit new snapshots
        run: |
          git add '*/snapshots/images/*'
          git commit -m "chore: rerecord screenshot tests"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
