name: Test E2E

on:
  push:
    paths-ignore:
      - "**.md"
  workflow_call:
  workflow_dispatch:

jobs:
  test-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: false
          android: false
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: true

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - id: setup
        uses: ./.github/actions/setup

      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      # If I ever need to diagnose a crash that's not reported in logcat
#      - name: Decrypt debug Google Services file
#        run: echo "${{ secrets.GOOGLE_SERVICES_DEBUG_JSON_BASE64 }}" | base64 -d > android/app/google-services.json

      - name: Install app on emulator, run Maestro tests
        id: test
        uses: reactivecircus/android-emulator-runner@v2.33.0
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_3a
          emulator-options: -memory 4096 -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          sdcard-path-or-size: 100M
          script: |
            ./gradlew installFDroidDebug
            adb shell settings put system show_touches 1
            adb shell cmd overlay enable com.android.internal.systemui.navbar.gestural
            adb shell cmd overlay disable com.android.internal.systemui.navbar.threebutton
            $HOME/.maestro/bin/maestro test .maestro/pr
            adb logcat -d --pid=$(adb shell pidof -s io.github.lydavid.musicsearch.debug) "*:E" > logcat
            adb shell "run-as io.github.lydavid.musicsearch.debug cat /data/data/io.github.lydavid.musicsearch.debug/databases/musicsearch.db" > musicsearch.db

      - name: Move all potential artifacts to one place
        run: |
          mkdir -p artifacts
          mv /home/runner/.maestro/tests/ artifacts
          mv *.mp4 artifacts
          [ -f logcat ] && mv logcat artifacts
          mv *.db artifacts

      - name: Save recordings
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: musicsearch_test_e2e_outputs
          path: artifacts
