name: Test E2E

on:
  push:
  workflow_dispatch:

jobs:
  test-e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - id: setup
        uses: ./.github/actions/setup

      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Install app on emulator, run Maestro tests
        id: test
        uses: reactivecircus/android-emulator-runner@v2.30.1
        with:
          api-level: 31
          arch: x86_64
          profile: pixel_3a
          heap-size: 512M
          ram-size: 4096M
          emulator-options: -memory 4096 -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          disk-size: 4G
          script: |
            ./gradlew installDebug
            $HOME/.maestro/bin/maestro test .maestro

      - name: Store outputs on failure
        if: steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: maestro_outputs
          path: $HOME/.maestro/tests
