name: Unit tests
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Grant permissions to gradlew
        run: chmod +x gradlew

      - name: Run unit tests with coverage
        run: ./gradlew data-android:createDebugUnitTestCoverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # TODO: Find a way to run the unit tests inside data (non-Android module)
