name: Update licenses

on:
  push:
    branches:
      - main
    paths:
      - "**/libs.versions.toml"
  workflow_call:
    secrets:
      PAT:
        required: true
  workflow_dispatch:

jobs:
  update-licenses:
    name: Update aboutlibraries.json for F-Droid release variant
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@f46300cd8952454b9f0a21a3d133d4bd5684cfc2 # v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - run: ./gradlew android:app:exportLibraryDefinitions -PaboutLibraries.exportVariant=fDroidRelease

      - name: Commit
        run: |
          git pull --autostash
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add '**\/aboutlibraries.json'
          git commit -m "chore: update licenses [skip ci]" || echo "No changes to commit"
          git push
