name: Update Schema Diagram

on:
  push:
#    paths:
#      - "*.sqm"
  workflow_dispatch:

jobs:
  update-schema-diagram:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - id: setup
        uses: ./.github/actions/setup

      - run: sudo apt install graphviz

      - name: Install app on emulator
        uses: reactivecircus/android-emulator-runner@v2.30.1
        with:
          api-level: 31
          arch: x86_64
          profile: pixel_3a
          heap-size: 512M
          ram-size: 4096M
          emulator-options: -memory 4096 -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          disk-size: 4G
          script: |
            ./gradlew installDebug
            adb shell "run-as io.github.lydavid.musicsearch.debug cat /data/data/io.github.lydavid.musicsearch.debug/databases/musicsearch.db" > musicsearch.db

      - name: Run SchemaCrawler Action with specified command-line
        uses: schemacrawler/SchemaCrawler-Action@v16.21.2
        with:
          entrypoint: /schemacrawler.sh
          args: --server=sqlite --database=musicsearch.db --info-level=standard --command=brief --output-file schema.svg --log-level=CONFIG

      - name: Upload SchemaCrawler database diagram
        uses: actions/upload-artifact@v2
        with:
          name: schema
          path: schema.svg
