name: Update module graph

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  regen:
    name: Regenerate graph
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - name: Regenerate module graph
        run: ./gradlew createModuleGraph

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: 'chore: update module graph [skip ci]'
          file_pattern: 'README.md'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
