name: Update licenses

on:
  push:
    branches:
      - main
    paths:
      - "**/libs.versions.toml"
  workflow_call:
    secrets:
      PAT:
        required: true
  workflow_dispatch:

jobs:
  update-licenses:
    name: Update aboutlibraries.json for F-Droid release variant
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@f46300cd8952454b9f0a21a3d133d4bd5684cfc2 # v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - run: ./gradlew android:app:exportLibraryDefinitions -PaboutLibraries.exportVariant=fDroidRelease

      - run: git pull --rebase --autostash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_message: 'chore: update licenses [skip ci]'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          file_pattern: '**/aboutlibraries.json'
