name: Update Schema Diagram

on:
  push:
    branches: ["main"]
    paths:
      - "**.sqm"
  workflow_dispatch:

jobs:
  update-schema-diagram:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - id: setup
        uses: ./.github/actions/setup

      - run: sudo apt install graphviz

      - name: Install app on emulator
        uses: reactivecircus/android-emulator-runner@v2.33.0
        with:
          api-level: 31
          arch: x86_64
          profile: pixel_3a
          heap-size: 512M
          ram-size: 4096M
          emulator-options: -memory 4096 -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          disk-size: 4G
          script: |
            ./gradlew installFDroidDebug
            # Installing is not enough to initialize the SQLDelight database, need to launch the app
            adb shell am start -a android.intent.action.VIEW -d "io.github.lydavid.musicsearch.debug://app/history"
            sleep 10
            adb shell "run-as io.github.lydavid.musicsearch.debug cat /data/data/io.github.lydavid.musicsearch.debug/databases/musicsearch.db" > musicsearch.db

      - name: Generate schema SVG from sqlite file
        uses: schemacrawler/SchemaCrawler-Action@v16.25.2
        with:
          entrypoint: /schemacrawler.sh
          args: --server=sqlite --database=musicsearch.db --info-level=maximum --command=schema --output-file assets/musicsearch_db_schema.svg --log-level=CONFIG

      - run: git pull --rebase --autostash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: 'chore: update schema diagram [skip ci]'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          file_pattern: 'assets/musicsearch_db_schema.svg'
