name: Update dependency graph

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.kts"
  workflow_call:
    secrets:
      PAT:
        required: true
  workflow_dispatch:

jobs:
  update-dependency-graph:
    name: Update dependency graph
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@f46300cd8952454b9f0a21a3d133d4bd5684cfc2 # v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - run: sudo apt install graphviz

      - run: ./gradlew generateProjectReadme

      - run: git pull --rebase --autostash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: 'chore: update module dependency graph [skip ci]'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
