name: Update dependency graph

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.kts"
  workflow_call:
    secrets:
      PAT:
        required: true
  workflow_dispatch:

jobs:
  update-dependency-graph:
    name: Update dependency graph
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@f46300cd8952454b9f0a21a3d133d4bd5684cfc2 # v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - run: sudo apt install graphviz

      - run: ./gradlew generateProjectReadme

      - name: Commit
        run: |
          git pull --autostash
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "chore: update module dependency graph [skip ci]" || echo "No changes to commit"
          git push
