name: Update dependency graph

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-dependency-graph:
    name: Update dependency graph
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - id: setup
        uses: ./.github/actions/setup

      - run: sudo apt install graphviz

      - run: ./gradlew projectDependencyGraph

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: 'chore: update module dependency graph [skip ci]'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
