name: Update compose compiler report

on:
  schedule:
    - cron: '42 6 * * *'
  push:
    branches:
      - "dl/compose-compiler-report" # TODO: remove
  workflow_dispatch:

jobs:
  update-compose-compiler-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ORG_GRADLE_PROJECT_MUSICBRAINZ_CLIENT_ID: ${{ secrets.ORG_GRADLE_PROJECT_MUSICBRAINZ_CLIENT_ID }}
      ORG_GRADLE_PROJECT_MUSICBRAINZ_CLIENT_SECRET: ${{ secrets.ORG_GRADLE_PROJECT_MUSICBRAINZ_CLIENT_SECRET }}
      ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_ID: ${{ secrets.ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_ID }}
      ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_SECRET: ${{ secrets.ORG_GRADLE_PROJECT_SPOTIFY_CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          token: ${{ secrets.PAT }}

      - name: Setup gradle
        uses: ./.github/actions/setup

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install -g compose-report2html

      - name: Write to keystore.properties
        run: |
          echo "storePassword=${{ secrets.RELEASE_STORE_PASSWORD }}" >> keystore.properties
          echo "keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> keystore.properties
        shell: bash

      - name: Convert base64 to files
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d >> app/google-services.json
          echo "${{ secrets.RELEASE_KEYSTORE_JKS_BASE64 }}" | base64 -d >> release-keystore.jks
        shell: bash

      - name: Assemble apk with compose compiler reports enabled
        run: ./gradlew assembleRelease -Pmbjc.enableComposeCompilerReports=true --rerun-tasks

      - name: Generated HTML from compose reports
        run: find . -type d -path '*/build/compose_metrics' | xargs -I {} composeReport2Html -app MusicSearch -i {} -o {}

      - name: Move the compose reports and HTML file to each module's root
        run: find . -type d -path '*/build/compose_metrics' -exec bash -c 'mv {}/* "$(dirname "$(dirname {})")"' \;

      - name: Commit version code bump
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: 'chore: update compose compiler report [skip ci]'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
